[graph]
targets = ["x86_64-unknown-linux-musl"]
all-features = true

[licenses]
# See https://spdx.org/licenses/ for list of possible licenses
allow = [
    "Apache-2.0",
    "MIT",
    "Unicode-3.0",
]
confidence-threshold = 0.9
private = { ignore = true }

[bans]
multiple-versions = "deny"
wildcards = "deny"
skip = [
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
