[graph]
targets = ["x86_64-unknown-linux-musl"]
all-features = true

[licenses]
# See https://spdx.org/licenses/ for list of possible licenses
allow = [
    # "Apache-2.0",
    # "BSD-2-Clause",
    # "BSD-3-Clause",
    # "BSL-1.0",
    # "ISC",
    # "MIT",
    # "MPL-2.0",
    # "Unicode-3.0",
    # "Unlicense",
    # "Zlib",
]
confidence-threshold = 0.9
private = { ignore = true }

# Copied from cargo-deny's own deny.toml
[[licenses.clarify]]
crate = "ring"
# SPDX considers OpenSSL to encompass both the OpenSSL and SSLeay licenses
# https://spdx.org/licenses/OpenSSL.html
# ISC - Both BoringSSL and ring use this for their new files
# MIT - "Files in third_party/ have their own licenses, as described therein. The MIT
# license, for third_party/fiat, which, unlike other third_party directories, is
# compiled into non-test libraries, is included below."
# OpenSSL - Obviously
expression = "ISC AND MIT AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[bans]
multiple-versions = "deny"
wildcards = "deny"
skip = []
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
# allow-org = { github = ["nos-digital"] }
