pub const SECONDS_PER_DAY: u32 = SECONDS_PER_HOUR * 24;
pub const SECONDS_PER_HOUR: u32 = SECONDS_PER_MINUTE * 60;
pub const SECONDS_PER_MINUTE: u32 = 60;

pub const NANOS_PER_SECOND: u32 = 999_999_999;

pub const MONTHS_PER_YEAR: u32 = 12;
pub const DAYS_PER_WEEK: u32 = 7;

pub const DAYS_IN_YEAR_COMMON: u32 = DAYS_SINCE_COMMON_DECEMBER + DAYS_IN_DECEMBER;
pub const DAYS_IN_YEAR_LEAP: u32 = DAYS_SINCE_LEAP_DECEMBER + DAYS_IN_DECEMBER;

pub const DAYS_IN_JANUARY: u32 = 31;
pub const DAYS_IN_COMMON_FEBRUARY: u32 = 28;
pub const DAYS_IN_LEAP_FEBRUARY: u32 = 29;
pub const DAYS_IN_MARCH: u32 = 31;
pub const DAYS_IN_APRIL: u32 = 30;
pub const DAYS_IN_MAY: u32 = 31;
pub const DAYS_IN_JUNE: u32 = 30;
pub const DAYS_IN_JULY: u32 = 31;
pub const DAYS_IN_AUGUST: u32 = 31;
pub const DAYS_IN_SEPTEMBER: u32 = 30;
pub const DAYS_IN_OCTOBER: u32 = 31;
pub const DAYS_IN_NOVEMBER: u32 = 30;
pub const DAYS_IN_DECEMBER: u32 = 31;

pub const DAYS_IN_COMMON_MONTH: [u32; 12] = [
    DAYS_IN_JANUARY,
    DAYS_IN_COMMON_FEBRUARY,
    DAYS_IN_MARCH,
    DAYS_IN_APRIL,
    DAYS_IN_MAY,
    DAYS_IN_JUNE,
    DAYS_IN_JULY,
    DAYS_IN_AUGUST,
    DAYS_IN_SEPTEMBER,
    DAYS_IN_OCTOBER,
    DAYS_IN_NOVEMBER,
    DAYS_IN_DECEMBER,
];
pub const DAYS_IN_LEAP_MONTH: [u32; 12] = [
    DAYS_IN_JANUARY,
    DAYS_IN_LEAP_FEBRUARY,
    DAYS_IN_MARCH,
    DAYS_IN_APRIL,
    DAYS_IN_MAY,
    DAYS_IN_JUNE,
    DAYS_IN_JULY,
    DAYS_IN_AUGUST,
    DAYS_IN_SEPTEMBER,
    DAYS_IN_OCTOBER,
    DAYS_IN_NOVEMBER,
    DAYS_IN_DECEMBER,
];

pub const DAYS_SINCE_JANUARY: u32 = 0;
pub const DAYS_SINCE_FEBRUARY: u32 = DAYS_SINCE_JANUARY + DAYS_IN_JANUARY;

pub const DAYS_SINCE_COMMON_JANUARY: u32 = DAYS_SINCE_JANUARY;
pub const DAYS_SINCE_COMMON_FEBRUARY: u32 = DAYS_SINCE_FEBRUARY;
pub const DAYS_SINCE_COMMON_MARCH: u32 = DAYS_SINCE_FEBRUARY + DAYS_IN_COMMON_FEBRUARY;
pub const DAYS_SINCE_COMMON_APRIL: u32 = DAYS_SINCE_COMMON_MARCH + DAYS_IN_MARCH;
pub const DAYS_SINCE_COMMON_MAY: u32 = DAYS_SINCE_COMMON_APRIL + DAYS_IN_APRIL;
pub const DAYS_SINCE_COMMON_JUNE: u32 = DAYS_SINCE_COMMON_MAY + DAYS_IN_MAY;
pub const DAYS_SINCE_COMMON_JULY: u32 = DAYS_SINCE_COMMON_JUNE + DAYS_IN_JUNE;
pub const DAYS_SINCE_COMMON_AUGUST: u32 = DAYS_SINCE_COMMON_JULY + DAYS_IN_JULY;
pub const DAYS_SINCE_COMMON_SEPTEMBER: u32 = DAYS_SINCE_COMMON_AUGUST + DAYS_IN_AUGUST;
pub const DAYS_SINCE_COMMON_OCTOBER: u32 = DAYS_SINCE_COMMON_SEPTEMBER + DAYS_IN_SEPTEMBER;
pub const DAYS_SINCE_COMMON_NOVEMBER: u32 = DAYS_SINCE_COMMON_OCTOBER + DAYS_IN_OCTOBER;
pub const DAYS_SINCE_COMMON_DECEMBER: u32 = DAYS_SINCE_COMMON_NOVEMBER + DAYS_IN_NOVEMBER;

pub const DAYS_SINCE_LEAP_JANUARY: u32 = DAYS_SINCE_JANUARY;
pub const DAYS_SINCE_LEAP_FEBRUARY: u32 = DAYS_SINCE_FEBRUARY;
pub const DAYS_SINCE_LEAP_MARCH: u32 = DAYS_SINCE_LEAP_FEBRUARY + DAYS_IN_LEAP_FEBRUARY;
pub const DAYS_SINCE_LEAP_APRIL: u32 = DAYS_SINCE_LEAP_MARCH + DAYS_IN_MARCH;
pub const DAYS_SINCE_LEAP_MAY: u32 = DAYS_SINCE_LEAP_APRIL + DAYS_IN_APRIL;
pub const DAYS_SINCE_LEAP_JUNE: u32 = DAYS_SINCE_LEAP_MAY + DAYS_IN_MAY;
pub const DAYS_SINCE_LEAP_JULY: u32 = DAYS_SINCE_LEAP_JUNE + DAYS_IN_JUNE;
pub const DAYS_SINCE_LEAP_AUGUST: u32 = DAYS_SINCE_LEAP_JULY + DAYS_IN_JULY;
pub const DAYS_SINCE_LEAP_SEPTEMBER: u32 = DAYS_SINCE_LEAP_AUGUST + DAYS_IN_AUGUST;
pub const DAYS_SINCE_LEAP_OCTOBER: u32 = DAYS_SINCE_LEAP_SEPTEMBER + DAYS_IN_SEPTEMBER;
pub const DAYS_SINCE_LEAP_NOVEMBER: u32 = DAYS_SINCE_LEAP_OCTOBER + DAYS_IN_OCTOBER;
pub const DAYS_SINCE_LEAP_DECEMBER: u32 = DAYS_SINCE_LEAP_NOVEMBER + DAYS_IN_NOVEMBER;

pub const DAYS_SINCE_COMMON_MONTH: [u32; 12] = [
    DAYS_SINCE_COMMON_JANUARY,
    DAYS_SINCE_FEBRUARY,
    DAYS_SINCE_COMMON_MARCH,
    DAYS_SINCE_COMMON_APRIL,
    DAYS_SINCE_COMMON_MAY,
    DAYS_SINCE_COMMON_JUNE,
    DAYS_SINCE_COMMON_JULY,
    DAYS_SINCE_COMMON_AUGUST,
    DAYS_SINCE_COMMON_SEPTEMBER,
    DAYS_SINCE_COMMON_OCTOBER,
    DAYS_SINCE_COMMON_NOVEMBER,
    DAYS_SINCE_COMMON_DECEMBER,
];
pub const DAYS_SINCE_LEAP_MONTH: [u32; 12] = [
    DAYS_SINCE_LEAP_JANUARY,
    DAYS_SINCE_LEAP_FEBRUARY,
    DAYS_SINCE_LEAP_MARCH,
    DAYS_SINCE_LEAP_APRIL,
    DAYS_SINCE_LEAP_MAY,
    DAYS_SINCE_LEAP_JUNE,
    DAYS_SINCE_LEAP_JULY,
    DAYS_SINCE_LEAP_AUGUST,
    DAYS_SINCE_LEAP_SEPTEMBER,
    DAYS_SINCE_LEAP_OCTOBER,
    DAYS_SINCE_LEAP_NOVEMBER,
    DAYS_SINCE_LEAP_DECEMBER,
];
